# Generated by Django 2.2.6 on 2019-11-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(max_length=75)),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('kilometraje', models.PositiveIntegerField(default=0)),
                ('nuevo', models.BooleanField(default=True)),
                ('tipo', models.CharField(default='Avion', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(max_length=75)),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('kilometraje', models.PositiveIntegerField(default=0)),
                ('nuevo', models.BooleanField(default=True)),
                ('tipo', models.CharField(default='Carro', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
